Repository JuliaZhang7/17313_project2, pull requests merged in 2023-03, with the labels that each got.

#31 fixing resolve.ts to pass lint
  src/posts/resolve.ts
Labels: us2

#28 Added Tag array dependency to display tags
  themes/nodebb-theme-persona/templates/recent.tpl
Labels: us1

#32 Added Tag array dependency to display tags
  themes/nodebb-theme-persona/templates/recent.tpl
Labels: us1

#36 Poll plug in created for Nodebb
  UserGuide.md
  nodebb-plugin-poll-git/.editorconfig
  nodebb-plugin-poll-git/.eslintrc
  nodebb-plugin-poll-git/.gitignore
  nodebb-plugin-poll-git/LICENSE
  nodebb-plugin-poll-git/README.md
  nodebb-plugin-poll-git/languages/cs/poll.json
  nodebb-plugin-poll-git/languages/de/poll.json
  nodebb-plugin-poll-git/languages/en_GB/poll.json
  nodebb-plugin-poll-git/languages/en_US/poll.json
  nodebb-plugin-poll-git/languages/es/poll.json
  nodebb-plugin-poll-git/languages/fr/poll.json
  nodebb-plugin-poll-git/languages/gl/poll.json
  nodebb-plugin-poll-git/languages/he/poll.json
  nodebb-plugin-poll-git/languages/it/poll.json
  nodebb-plugin-poll-git/languages/pl/poll.json
  nodebb-plugin-poll-git/languages/pt-PT/poll.json
  nodebb-plugin-poll-git/languages/ro/poll.json
  nodebb-plugin-poll-git/languages/ru/poll.json
  nodebb-plugin-poll-git/languages/tr/poll.json
  nodebb-plugin-poll-git/languages/zh_CN/poll.json
  nodebb-plugin-poll-git/lib/config.js
  nodebb-plugin-poll-git/lib/hooks.js
  nodebb-plugin-poll-git/lib/nodebb.js
  nodebb-plugin-poll-git/lib/poll.js
  nodebb-plugin-poll-git/lib/scheduler.js
  nodebb-plugin-poll-git/lib/serializer.js
  nodebb-plugin-poll-git/lib/sockets.js
  nodebb-plugin-poll-git/lib/vote.js
  nodebb-plugin-poll-git/library.js
  nodebb-plugin-poll-git/package.json
  nodebb-plugin-poll-git/plugin.json
  nodebb-plugin-poll-git/public/js/.eslintrc
  nodebb-plugin-poll-git/public/js/admin.js
  nodebb-plugin-poll-git/public/js/poll/creator.js
  nodebb-plugin-poll-git/public/js/poll/main.js
  nodebb-plugin-poll-git/public/js/poll/serializer.js
  nodebb-plugin-poll-git/public/js/poll/sockets.js
  nodebb-plugin-poll-git/public/js/poll/view.js
  nodebb-plugin-poll-git/public/scss/style.scss
  nodebb-plugin-poll-git/templates/admin/plugins/poll.tpl
  nodebb-plugin-poll-git/templates/poll/creator.tpl
  nodebb-plugin-poll-git/templates/poll/view.tpl
  nodebb-plugin-poll-git/templates/poll/view/details.tpl
  nodebb-plugin-poll-git/templates/poll/view/messages.tpl
  nodebb-plugin-poll-git/templates/poll/view/results.tpl
  nodebb-plugin-poll-git/templates/poll/view/voting.tpl
  nodebb-plugin-poll-git/upgrades/convert_poll_id_voters_and_options_votes_to_sorted_sets.js
  nodebb-plugin-poll-git/upgrades/fix_incorrect_poll_privilege.js
  nodebb-plugin-poll-git/upgrades/give_categories_poll_create_privs_to_reg_users.js
  nodebb-plugin-poll-git/vendor/dayjs.min.js
  nodebb-plugin-poll-git/vendor/flatpickr.l10n.js
  nodebb-plugin-poll-git/vendor/flatpickr.min.css
  nodebb-plugin-poll-git/vendor/flatpickr.min.js
  src/posts/resolve.js
Labels: documentation, US

#37 User Guide documentation
  userGuide.md
Labels: documentation

#21 Created tagFilter.js in public/src/modules
  public/src/modules/tagFilter.ts
  test/tags.js
  themes/nodebb-theme-persona/templates/partials/tags-filter-right.tpl
  themes/nodebb-theme-persona/templates/partials/topic/sort.tpl
  themes/nodebb-theme-persona/templates/recent.tpl
Labels: us1

#25 File changes made for 'Mark as Resolved' backend implementation
  .husky/commit-msg
  .husky/pre-commit
  nodebb
  src/posts/index.js
  src/posts/resolve.ts
  src/routes/write/posts.js
  src/views/partials/fontawesome.tpl
  themes/nodebb-theme-persona/templates/partials/topic/post-menu-list.tpl
Labels: us2

#39 Delete UserGuide.md
  UserGuide.md
Labels: documentation

#40 Update and rename userGuide.md to UserGuide.md
  UserGuide.md
Labels: documentation
